### ISSUE TITLE
handshake_params should be a literal type

### ISSUE THREAD

**Issue by anarthal** [boostorg/mysql#176]
There is no reason why handshake_params couldn't have all member functions constexpr.

**Comment by marco-langer** [comment]
The type `handshake_params` seems to have no class invariants and is just a collection of data ("pod"). Usually one would argue that it should be a struct instead of a class, see also [C++ Core Guideline C.2](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-struct). 

That would make the need for constexpr getter/setter obsolete but would break the current API.

**Comment by anarthal** [comment]
I'm actually writing a type-erased connection which is probably gonna become the new standard connection - and uses a raw struct for this purpose.

**Comment by anarthal** [comment]
Boost 1.87 will make `any_connection` stable, and it's the way to go. This is no longer relevant.
