### ISSUE TITLE
Using boost.mysql in dynamic libraries may cause crashes

### ISSUE THREAD

**Issue by jphz** [boostorg/mysql#318]
![image](https://github.com/user-attachments/assets/539169be-cbcd-4893-b4ad-fe3cfb33a302)
Triggered an unprocessed exception: write access permission conflict.
N is null ptr.

**Comment by jphz** [comment]
There will not be such issues when using in a static library.

**Comment by jphz** [comment]
I am very confused and hope to receive an answer.

**Comment by anarthal** [comment]
A possible cause for your problem is having different versions of your libraries in the DLL you're building and in your main. Check that:
- You're using the same standard library for both your main and your DLL. MSVC comes with [different standard library versions](https://learn.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170) that are not compatible with each other.
- You're using different configuration switches for your main and your DLL. For instance, defining a BOOST_ASIO_XXXX macro on one, and not the other.

If that doesn't solve the problem, I'd need more information to investigate. That'd include your compiler version, build flags, whether you're using Boost.MySQL only in your DLL or also in your main, and whether you're using other Boost libraries in your main.

**Comment by anarthal** [comment]
Any news on this? Was the issue solved?

**Comment by anarthal** [comment]
Closing this now.
